.\" QSHELL MANUAL - WRITTEN BY CHRIS PONTICELLO
.TH "QSHELL" "1" "2013-08-19" "COMP3301 Assignment 1" "User Commands"
.SH NAME
qshell \- COMP3301 Operating Systems Shell project
.SH SYNOPSIS
.B qshell
[\fIFILE\fR]
.SH DESCRIPTION
\fBqshell\fR is a minimalist shell program. It works similarly to \fBbash\fR, prompting for a command line and running commands, but does not have many of the special features of the \fBbash\fR shell.
.PP
\fBqshell\fR supports redirection of standard input/output (< >), use of unnamed pipes (|), background processes (&) and comments (#). It includes two built-in commands, \fBexit\fR and \fBcd\fR.
.PP
If a \fIFILE\fR argument is given, commands are read from the \fIFILE\fR; otherwise, \fBqshell\fR launches in interactive mode and prompts for commands.
.SH OPTIONS
.SH EXIT STATUS
.TP
0
if OK,
.TP
1
for minor problems (e.g. cannot access \fIFILE\fR given)
.TP
2
for serious trouble (e.g. memory issues, internal errors)
.SH ENVIRONMENT
The behaviour of \fBqshell\fR is affected by the following environment variables.
.IP "\fBPATH\fR" 4
.IX Item "PATH"
The path
.IP "\fBHOME\fR" 4
.IX Item "HOME"
The home
.SH FILES
.IX Header "FILES"
.IP "\fBqshell\fR" 4
.IX Item "qshell"
The executable binary.
.IP "No external files are required" 4
.IX Item "No external files"
.SH NOTES
.SH BUGS
\-
.SH EXAMPLES
.SH AUTHOR
Written by Chris Ponticello. christopher.ponticello@uqconnect.edu.au
.SH SEE ALSO
.TP
bash(1), cd(1), exit(1)
